### ISSUE TITLE
Doesn't work on CentOS7

### ISSUE THREAD

**Issue by memset-0x00** [moonbaseDelta/OSfooler-ng#16]
This does not work at all, after installing all the required libraries.

ERROR: Loading module scapy.layers.mspac
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/scapy/main.py", line 156, in _load
    mod = importlib.import_module(module)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/scapy/layers/mspac.py", line 482, in <module>
    class CLAIM_ENTRY(NDRPacket):
  File "/usr/lib/python2.7/site-packages/scapy/layers/mspac.py", line 486, in CLAIM_ENTRY
    NDRInt3264EnumField("Type", 0, CLAIM_TYPE),
  File "/usr/lib/python2.7/site-packages/scapy/layers/dcerpc.py", line 1102, in __init__
    _NDREnumField(*args, **kwargs), align=(2, 4)
  File "/usr/lib/python2.7/site-packages/scapy/fields.py", line 2471, in __init__
    value = cast(str, enum[k])  # type: ignore
  File "/usr/lib/python2.7/site-packages/enum/__init__.py", line 376, in __getitem__
    return cls._member_map_[name]
KeyError: <CLAIM_TYPE.CLAIM_TYPE_INT64: 1>

What does CLAIM_TYPE.CLAIM_TYPE_INT64 even mean?

**Comment by memset-0x00** [comment]
Requires enum34
